### ISSUE TITLE
Task list changes

### ISSUE THREAD

**Issue by yogeshkudikala** [madrecha/jamku#986]
- [x] By default hide taskname 2, descp, clientid, groupid, serviced,
- [x] All categories hide by default and select filter instead of text
- [x] Rename column task status to status, task priority to priority
